language: php

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  - DB=mysql
  - DB=sqlite

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

before_script:
  - if [[ $DB == 'mysql' && $MYSQL_VERSION == '5.7' ]]; then ./tests/travis/install-mysql-5.7.sh; fi
  - if [[ $DB == 'mysql' ]]; then mysql -e 'select version()'; fi

script: ./vendor/bin/phpunit -c tests/travis/$DB.travis.xml

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest" DB=sqlite
    - php: 7.0
      env: DB=mysql
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - mysql-server-5.6
          - mysql-client-core-5.6
          - mysql-client-5.6
    - php: 7.0
      env: DB=mysql MYSQL_VERSION=5.7
      sudo: required
  allow_failures:
    - php: nightly
    - php: hhvm
